name: flow-sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: fetch_latest
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          url=$(gh release view --repo mykso/myks --json name,assets --jq '.assets[] | select(.url | contains("darwin_amd64")) | .url')
          dirty_version=$(gh release view --repo mykso/myks --json name,assets --jq '.name')
          version=${dirty_version/#v}

          echo "RELEASE_URL=$url" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$version" >> $GITHUB_ENV
      - name: print_latest
        run: |
          echo "Release ($RELEASE_VERSION) asset URL: $RELEASE_URL"
      - name: brew_update
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
        run: |
          brew tap yserz/tap
          brew install myks
          brew bump-formula-pr --write-only --version $RELEASE_VERSION --url $RELEASE_URL myks

          updated_formula_path=$(HOMEBREW_NO_INSTALL_FROM_API=1 brew edit myks --print-path)
          cat $updated_formula_path
          mv updated_formula_path myks.rb

          git diff origin/main
