name: flow-sync

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  latest-release-version:
    uses: ./.github/workflows/job-latest-release-version.yml
    with:
      REPO_OWNER: mykso
      REPO_NAME: myks
  update-formula:
    uses: ./.github/workflows/job-update-formula.yml
    needs: [latest-release-version]
    with:
      FORMULA_NAME: myks
      RELEASE_VERSION: ${{ needs.latest-release-version.outputs.RELEASE_VERSION }}
      ARTIFACT_ID: updated-formula
  commit:
    uses: ./.github/workflows/job-commit.yml
    needs: [latest-release-version, update-formula]
    with:
      COMMIT_MESSAGE: "chore: update myks to ${{ needs.latest-release-version.outputs.RELEASE_VERSION }}"
      ARTIFACT_ID: updated-formula
      DRYRUN: ${{ github.event_name == 'pull_request' }}
